"""initial schema: jobs, agent_runs, agent_logs

Hand-written rather than autogenerated, because autogenerate does not reliably
emit CREATE TYPE / DROP TYPE for native Postgres enums.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-26
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# `create_type=False` prevents a second CREATE TYPE attempt when create_table
# runs; the types are created explicitly below. Omitting it raises
# `DuplicateObject: type "job_status" already exists`.
JOB_STATUS = postgresql.ENUM(
    "queued", "running", "completed", "failed",
    name="job_status", create_type=False,
)
AGENT_STATUS = postgresql.ENUM(
    "idle", "queued", "running", "completed", "failed", "retrying",
    name="agent_status", create_type=False,
)
LOG_LEVEL = postgresql.ENUM(
    "info", "warn", "error", name="log_level", create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    JOB_STATUS.create(bind, checkfirst=True)
    AGENT_STATUS.create(bind, checkfirst=True)
    LOG_LEVEL.create(bind, checkfirst=True)

    op.create_table(
        "jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("task_description", sa.Text(), nullable=False),
        sa.Column("status", JOB_STATUS, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("final_output", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
    )
    # Job queue list view: filter by status, sort by recency (TECH_SPEC 4.2).
    op.create_index(
        "ix_jobs_status_created_at",
        "jobs",
        ["status", sa.text("created_at DESC")],
    )

    op.create_table(
        "agent_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("agent_name", sa.Text(), nullable=False),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column("status", AGENT_STATUS, nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rework_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "input_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "output_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
    )
    # Ordered pipeline reconstruction for the run detail view (TECH_SPEC 4.2).
    op.create_index(
        "ix_agent_runs_job_id_sequence",
        "agent_runs",
        ["job_id", "sequence_index"],
    )

    op.create_table(
        "agent_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("agent_run_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("agent_name", sa.Text(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("level", LOG_LEVEL, nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
    )
    # Chronological retrieval and `?since=` cursor pagination (TECH_SPEC 4.2).
    op.create_index(
        "ix_agent_logs_job_id_timestamp",
        "agent_logs",
        ["job_id", "timestamp"],
    )


def downgrade() -> None:
    # Tables first, then the enum types they depend on.
    op.drop_index("ix_agent_logs_job_id_timestamp", table_name="agent_logs")
    op.drop_table("agent_logs")

    op.drop_index("ix_agent_runs_job_id_sequence", table_name="agent_runs")
    op.drop_table("agent_runs")

    op.drop_index("ix_jobs_status_created_at", table_name="jobs")
    op.drop_table("jobs")

    bind = op.get_bind()
    postgresql.ENUM(name="log_level").drop(bind, checkfirst=True)
    postgresql.ENUM(name="agent_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="job_status").drop(bind, checkfirst=True)
